modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "Apache License"

[[mods]]
modId = "totem"
version = "${version}"
displayName = "TotemMod1181"
authors = "GingkoTreeX"
description = '''
...
'''
#logoFile = ""

[[dependencies.totem]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.totem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"
